/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package microsoft.line;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class suppView extends javax.swing.JFrame {

    /**
     * Creates new form suppView
     */
    public suppView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        registerC = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clientName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        softwareSelect = new javax.swing.JList<>();
        problemDescription = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        complete = new javax.swing.JButton();
        cancelCall = new javax.swing.JButton();
        registerE = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameEmployee = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        createE = new javax.swing.JButton();
        cancelE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        software = new javax.swing.JList<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        registerC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Support View -- Register Call");
        registerC.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Microsoft Customer Support System");
        registerC.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel1.setText("Problem");
        registerC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel2.setText("Name");
        registerC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, 20));
        registerC.add(clientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 180, -1));

        jLabel3.setText("Phone Number");
        registerC.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 20));

        clientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameActionPerformed(evt);
            }
        });
        registerC.add(clientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, -1));

        jLabel6.setText("Client Information");
        registerC.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        softwareSelect.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Word", "Excel", "Powerpoint", "DataBase", "Software", "Games" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(softwareSelect);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(problemDescription);

        registerC.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 520, 100));

        jLabel7.setText("Select software and describe the problem with it,");
        registerC.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, -1));

        complete.setText("Register ");
        complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeActionPerformed(evt);
            }
        });
        registerC.add(complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        cancelCall.setText("Cancel");
        cancelCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCallActionPerformed(evt);
            }
        });
        registerC.add(cancelCall, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jTabbedPane1.addTab("Register Call", registerC);

        registerE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Microsoft Customer Support System");
        registerE.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel9.setText("Support View -- Register Employee");
        registerE.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel10.setText("Name");
        registerE.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        registerE.add(nameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 320, -1));

        jLabel11.setText("Software");
        registerE.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        createE.setText("Register");
        createE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEActionPerformed(evt);
            }
        });
        registerE.add(createE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        cancelE.setText("Cancel");
        cancelE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEActionPerformed(evt);
            }
        });
        registerE.add(cancelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        software.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Word", "Excel", "Powerpoint", "DataBase", "Software", "Games", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(software);

        registerE.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 320, -1));

        jTabbedPane1.addTab("Register Employee", registerE);

        getContentPane().add(jTabbedPane1, "card4");

        jMenu3.setText("Quit");

        quit.setText("quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu3.add(quit);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitActionPerformed

    private void createEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEActionPerformed
        String name = nameEmployee.getText();
        String soft = software.getSelectedValue();
        Employee newE = functions.newEmployee(name, soft, mainWindow.ListE);
        if(newE!=null){
            mainWindow.ListE.addAtEnd(newE);
            JOptionPane.showMessageDialog(null,"Added Successfully");
        }
        else{
            JOptionPane.showMessageDialog(null,"Already two technicians in that software");
        }
        nameEmployee.setText("");
    }//GEN-LAST:event_createEActionPerformed

    private void cancelEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEActionPerformed
        nameEmployee.setText("");
        
    }//GEN-LAST:event_cancelEActionPerformed

    private void clientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameActionPerformed

    private void completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeActionPerformed
        String name = clientName.getText();
        int number = functions.validateNum(clientPhone.getText());
        String softw= softwareSelect.getSelectedValue();
        String problem = problemDescription.getText();
        if(number!=0){
        functions.NewCall(mainWindow.ListE, name, softw, number, problem);}
        else{JOptionPane.showMessageDialog(null, "ERROR \n Please enter valid information");}
    }//GEN-LAST:event_completeActionPerformed

    private void cancelCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCallActionPerformed
        clientName.setText("");
        clientPhone.setText("");
        problemDescription.setText("");
    }//GEN-LAST:event_cancelCallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suppView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelCall;
    private javax.swing.JButton cancelE;
    private javax.swing.JTextField clientName;
    private javax.swing.JTextField clientPhone;
    private javax.swing.JButton complete;
    private javax.swing.JButton createE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameEmployee;
    private javax.swing.JTextField problemDescription;
    private javax.swing.JMenuItem quit;
    private javax.swing.JPanel registerC;
    private javax.swing.JPanel registerE;
    private javax.swing.JList<String> software;
    private javax.swing.JList<String> softwareSelect;
    // End of variables declaration//GEN-END:variables
}
