/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2;

/**
 *
 * @author andre
 */
public class ventanaPrincipal extends javax.swing.JFrame {
        public static long number;
        public static String numS;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        ventanaPrincipal.number=0;
        ventanaPrincipal.numS="";
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputScreen = new javax.swing.JTextField();
        One = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Seven = new javax.swing.JButton();
        Eigth = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Prime = new javax.swing.JButton();
        Perfect = new javax.swing.JButton();
        Even = new javax.swing.JButton();
        Factorial = new javax.swing.JButton();
        outputScreen = new javax.swing.JTextField();
        clearInput = new javax.swing.JButton();
        clearOutput = new javax.swing.JButton();
        quit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to this calculator!");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 90));

        inputScreen.setEditable(false);
        inputScreen.setBackground(new java.awt.Color(204, 204, 255));
        inputScreen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputScreen.setForeground(new java.awt.Color(0, 51, 51));
        inputScreen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputScreen.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        inputScreen.setSelectionColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(inputScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 360, 60));

        One.setBackground(new java.awt.Color(0, 51, 51));
        One.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        One.setForeground(new java.awt.Color(204, 204, 255));
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });
        jPanel1.add(One, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, -1));

        Two.setBackground(new java.awt.Color(0, 51, 51));
        Two.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Two.setForeground(new java.awt.Color(204, 204, 255));
        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });
        jPanel1.add(Two, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, -1));

        Three.setBackground(new java.awt.Color(0, 51, 51));
        Three.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Three.setForeground(new java.awt.Color(204, 204, 255));
        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });
        jPanel1.add(Three, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 80, -1));

        Four.setBackground(new java.awt.Color(0, 51, 51));
        Four.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Four.setForeground(new java.awt.Color(204, 204, 255));
        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });
        jPanel1.add(Four, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 80, -1));

        Five.setBackground(new java.awt.Color(0, 51, 51));
        Five.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Five.setForeground(new java.awt.Color(204, 204, 255));
        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });
        jPanel1.add(Five, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, -1));

        Six.setBackground(new java.awt.Color(0, 51, 51));
        Six.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Six.setForeground(new java.awt.Color(204, 204, 255));
        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });
        jPanel1.add(Six, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, -1));

        Seven.setBackground(new java.awt.Color(0, 51, 51));
        Seven.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Seven.setForeground(new java.awt.Color(204, 204, 255));
        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });
        jPanel1.add(Seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, -1));

        Eigth.setBackground(new java.awt.Color(0, 51, 51));
        Eigth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Eigth.setForeground(new java.awt.Color(204, 204, 255));
        Eigth.setText("8");
        Eigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EigthActionPerformed(evt);
            }
        });
        jPanel1.add(Eigth, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, -1));

        Nine.setBackground(new java.awt.Color(0, 51, 51));
        Nine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nine.setForeground(new java.awt.Color(204, 204, 255));
        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });
        jPanel1.add(Nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, -1));

        Zero.setBackground(new java.awt.Color(0, 51, 51));
        Zero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Zero.setForeground(new java.awt.Color(204, 204, 255));
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });
        jPanel1.add(Zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 80, -1));

        Prime.setBackground(new java.awt.Color(204, 204, 255));
        Prime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Prime.setForeground(new java.awt.Color(0, 51, 51));
        Prime.setText("Check if Prime");
        Prime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeActionPerformed(evt);
            }
        });
        jPanel1.add(Prime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 310, -1));

        Perfect.setBackground(new java.awt.Color(204, 204, 255));
        Perfect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Perfect.setForeground(new java.awt.Color(0, 51, 51));
        Perfect.setText("Check if Perfect");
        Perfect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfectActionPerformed(evt);
            }
        });
        jPanel1.add(Perfect, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 310, -1));

        Even.setBackground(new java.awt.Color(204, 204, 255));
        Even.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Even.setForeground(new java.awt.Color(0, 51, 51));
        Even.setText("Check if Even");
        Even.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvenActionPerformed(evt);
            }
        });
        jPanel1.add(Even, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 310, -1));

        Factorial.setBackground(new java.awt.Color(204, 204, 255));
        Factorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Factorial.setForeground(new java.awt.Color(0, 51, 51));
        Factorial.setText("Calculate Factorial");
        Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactorialActionPerformed(evt);
            }
        });
        jPanel1.add(Factorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 310, -1));

        outputScreen.setEditable(false);
        outputScreen.setBackground(new java.awt.Color(204, 204, 255));
        outputScreen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        outputScreen.setForeground(new java.awt.Color(0, 51, 51));
        outputScreen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputScreen.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        outputScreen.setSelectionColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(outputScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 310, 90));

        clearInput.setBackground(new java.awt.Color(204, 204, 255));
        clearInput.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clearInput.setForeground(new java.awt.Color(0, 51, 51));
        clearInput.setText("AC");
        clearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearInputActionPerformed(evt);
            }
        });
        jPanel1.add(clearInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 170, -1));

        clearOutput.setBackground(new java.awt.Color(0, 51, 51));
        clearOutput.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clearOutput.setForeground(new java.awt.Color(204, 204, 255));
        clearOutput.setText("Clear");
        clearOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOutputActionPerformed(evt);
            }
        });
        jPanel1.add(clearOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 310, -1));

        quit.setBackground(new java.awt.Color(0, 51, 51));
        quit.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        quit.setForeground(new java.awt.Color(204, 204, 255));
        quit.setText("X");
        quit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jPanel1.add(quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EigthActionPerformed
        ventanaPrincipal.numS=numS+"8";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_EigthActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        ventanaPrincipal.numS=numS+"1";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
        ventanaPrincipal.numS=numS+"2";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        ventanaPrincipal.numS=numS+"3";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        ventanaPrincipal.numS=numS+"4";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
       ventanaPrincipal.numS=numS+"5";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
        ventanaPrincipal.numS=numS+"6";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_SixActionPerformed

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        ventanaPrincipal.numS=numS+"7";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_SevenActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
        ventanaPrincipal.numS=numS+"9";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_NineActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        ventanaPrincipal.numS=numS+"0";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_ZeroActionPerformed

    private void clearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearInputActionPerformed
        ventanaPrincipal.numS="";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_clearInputActionPerformed

    private void PrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeActionPerformed
        auxiliars aux = new auxiliars(inputScreen.getText());
        outputScreen.setText(aux.IsPrime());
        
    }//GEN-LAST:event_PrimeActionPerformed

    private void PerfectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfectActionPerformed
        auxiliars aux = new auxiliars(inputScreen.getText());
        outputScreen.setText(aux.IsPerfect());
    }//GEN-LAST:event_PerfectActionPerformed

    private void EvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvenActionPerformed
        auxiliars aux = new auxiliars(inputScreen.getText());
        outputScreen.setText(aux.IsEven());
    }//GEN-LAST:event_EvenActionPerformed

    private void FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactorialActionPerformed
        auxiliars aux = new auxiliars(inputScreen.getText());
        outputScreen.setText(aux.GetFactorial());
    }//GEN-LAST:event_FactorialActionPerformed

    private void clearOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOutputActionPerformed
        outputScreen.setText("");
        ventanaPrincipal.numS="";
        inputScreen.setText(ventanaPrincipal.numS);
    }//GEN-LAST:event_clearOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eigth;
    private javax.swing.JButton Even;
    private javax.swing.JButton Factorial;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton Nine;
    private javax.swing.JButton One;
    private javax.swing.JButton Perfect;
    private javax.swing.JButton Prime;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton Zero;
    private javax.swing.JButton clearInput;
    private javax.swing.JButton clearOutput;
    private javax.swing.JTextField inputScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField outputScreen;
    private javax.swing.JButton quit;
    // End of variables declaration//GEN-END:variables
}
