/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andreina_rivas_quiz2;

/**
 *
 * @author andre
 */
public class mainWindow extends javax.swing.JFrame {
    
    public static Stack stack;
    public static String exclude;

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        stack = new Stack();
        exclude="";
        n_trees.setText("0");
        fail_message.setText("");
        print_message.setText("");
        merge_message.setText("");
        exclude_message.setText("");
        jLabel8.setVisible(false);
        jLabel6.setVisible(false);
        ex_num.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        n_nodos = new javax.swing.JTextField();
        name_tree = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        n_trees = new javax.swing.JLabel();
        create_tree = new javax.swing.JButton();
        merge_message = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mix_trees = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fail_message = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        name_mix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        preorder = new javax.swing.JTextArea();
        get_preorder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        excluded = new javax.swing.JTextArea();
        get_excluded = new javax.swing.JButton();
        print_message = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exclude_message = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ex_num = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 102, 0));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(n_nodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 61, 190, -1));
        jPanel2.add(name_tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Nombre del arbol:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        n_trees.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n_trees.setForeground(new java.awt.Color(0, 0, 0));
        n_trees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n_trees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        n_trees.setRequestFocusEnabled(false);
        jPanel2.add(n_trees, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 70, 70));
        n_trees.getAccessibleContext().setAccessibleDescription("");

        create_tree.setBackground(new java.awt.Color(51, 102, 0));
        create_tree.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        create_tree.setForeground(new java.awt.Color(255, 255, 255));
        create_tree.setText("Crear");
        create_tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_treeActionPerformed(evt);
            }
        });
        jPanel2.add(create_tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        merge_message.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        merge_message.setForeground(new java.awt.Color(51, 102, 0));
        merge_message.setText("jLabel3");
        jPanel2.add(merge_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 240, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 20, 220));

        mix_trees.setBackground(new java.awt.Color(51, 102, 0));
        mix_trees.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mix_trees.setForeground(new java.awt.Color(255, 255, 255));
        mix_trees.setText("Mezclar");
        mix_trees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mix_treesActionPerformed(evt);
            }
        });
        jPanel2.add(mix_trees, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Numero de nodos en el arbol:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Numero de arboles en el bosque:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        fail_message.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        fail_message.setForeground(new java.awt.Color(51, 102, 0));
        fail_message.setText("jLabel3");
        jPanel2.add(fail_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 300, -1));

        jTabbedPane1.addTab("Agregar Arbol", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(51, 102, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Preorden de la Mezcla:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        name_mix.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        name_mix.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(name_mix, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, 20));

        preorder.setColumns(20);
        preorder.setRows(5);
        jScrollPane1.setViewportView(preorder);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, 170));

        get_preorder.setBackground(new java.awt.Color(51, 102, 0));
        get_preorder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        get_preorder.setForeground(new java.awt.Color(255, 255, 255));
        get_preorder.setText("Imprimir");
        get_preorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_preorderActionPerformed(evt);
            }
        });
        jPanel4.add(get_preorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        excluded.setColumns(20);
        excluded.setRows(5);
        jScrollPane2.setViewportView(excluded);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 310, 170));

        get_excluded.setBackground(new java.awt.Color(51, 102, 0));
        get_excluded.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        get_excluded.setForeground(new java.awt.Color(255, 255, 255));
        get_excluded.setText("Imprimir");
        get_excluded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_excludedActionPerformed(evt);
            }
        });
        jPanel4.add(get_excluded, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        print_message.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        print_message.setForeground(new java.awt.Color(51, 102, 0));
        print_message.setText("jLabel6");
        jPanel4.add(print_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Valores excluidos:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        exclude_message.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        exclude_message.setForeground(new java.awt.Color(51, 102, 0));
        exclude_message.setText("jLabel6");
        jPanel4.add(exclude_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("Nombre del arbol:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("Numero de elementos excluidos:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        ex_num.setForeground(new java.awt.Color(0, 0, 0));
        ex_num.setText("jLabel9");
        jPanel4.add(ex_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jTabbedPane1.addTab("Imprimir Informacion", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 740, 350));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TU PROPIO BOSQUE BINARIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 60));

        close.setBackground(new java.awt.Color(51, 102, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setBorder(null);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 80, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_treeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_treeActionPerformed

        if(!n_nodos.getText().isEmpty()&&!name_tree.getText().isEmpty()){
            if(functions.valid_name(stack, name_tree.getText())){
                int nodos = functions.validate_number(n_nodos.getText());
                if(nodos<1000){
                    if(nodos!=-1 && nodos!=0){
                        Tree newT = functions.create_tree(name_tree.getText(), nodos);
                        stack.push(newT);
                        fail_message.setVisible(true);
                        fail_message.setText("Arbol "+newT.getName()+" creado con exito");
                        n_trees.setText(String.valueOf(stack.getSize()));
                    } else{
                        fail_message.setVisible(true);
                        fail_message.setText("Por favor ingrese un numero valido de nodos");
                    }
                }else{
                    fail_message.setVisible(true);
                    fail_message.setText("Por favor ingrese un numero de nodos menor a 1000");
                }

            }else{
                fail_message.setVisible(true);
                fail_message.setText("Ya existe un arbol con el nombre: "+name_tree.getText());
            }
            
        }else{
            fail_message.setVisible(true);
            fail_message.setText("Por favor complete todos los campos");
        }
        
        functions.reestart_create();
        mainWindow.print_message.setVisible(false);
        mainWindow.exclude_message.setVisible(false);
        mainWindow.merge_message.setVisible(false);
    }//GEN-LAST:event_create_treeActionPerformed

    private void mix_treesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mix_treesActionPerformed
        if(stack.getSize()!=1){
        functions.merge_forest(stack);
        n_trees.setText(String.valueOf(stack.getSize()));
        merge_message.setVisible(true);
        merge_message.setText("Mezcla completada");}
        else{
            merge_message.setVisible(true);
            merge_message.setText("No hay arboles que mezclar");
        }
        functions.reestart_create();
        mainWindow.print_message.setVisible(false);
        mainWindow.exclude_message.setVisible(false);
        mainWindow.fail_message.setVisible(false);
    }//GEN-LAST:event_mix_treesActionPerformed

    private void get_preorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_preorderActionPerformed

        if(!stack.isEmpty()){
            Tree tree = functions.get_oldest(stack);
            jLabel8.setVisible(true);
            preorder.setText(functions.print_merged(tree));
            name_mix.setVisible(true);
            name_mix.setText(tree.getName());
            print_message.setVisible(false);
        }else{
            print_message.setVisible(true);
            print_message.setText("No hay arboles añadidos");
            
        }
        mainWindow.exclude_message.setVisible(false);
        mainWindow.fail_message.setVisible(false);
        mainWindow.merge_message.setVisible(false);
    }//GEN-LAST:event_get_preorderActionPerformed

    private void get_excludedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_excludedActionPerformed
      
        if(!exclude.isEmpty()){
           excluded.setText(functions.print_excluded(exclude));
           jLabel6.setVisible(true);
           ex_num.setVisible(true);
           ex_num.setText(String.valueOf((exclude.split("\n")).length));
           exclude_message.setVisible(false);
       }else{
           exclude_message.setVisible(true);
           exclude_message.setText("No hay elementos excluidos");
       }
        mainWindow.print_message.setVisible(false);
         mainWindow.fail_message.setVisible(false);
        mainWindow.merge_message.setVisible(false);
    }//GEN-LAST:event_get_excludedActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton create_tree;
    private javax.swing.JLabel ex_num;
    public static javax.swing.JLabel exclude_message;
    public static javax.swing.JTextArea excluded;
    public static javax.swing.JLabel fail_message;
    private javax.swing.JButton get_excluded;
    private javax.swing.JButton get_preorder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel merge_message;
    private javax.swing.JButton mix_trees;
    public static javax.swing.JTextField n_nodos;
    private javax.swing.JLabel n_trees;
    public static javax.swing.JLabel name_mix;
    public static javax.swing.JTextField name_tree;
    public static javax.swing.JTextArea preorder;
    public static javax.swing.JLabel print_message;
    // End of variables declaration//GEN-END:variables
}
