/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andreina_rivas_quiz1;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class mainWindow extends javax.swing.JFrame {

    
    public static ShowList ShowList;
    public static File file;
    public static NodoS show;
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema! \n Recuerda cargar la informacion de las series disponibles \n en la ventana de Cargar Series antes de usar \n la plataforma");
        status.setText("Sin Informacion Cargada");
        jButton3.setVisible(false);
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        all = new javax.swing.JButton();
        child = new javax.swing.JButton();
        adult = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterOutput = new javax.swing.JTextArea();
        allbyEp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        showInput = new javax.swing.JTextField();
        searchShow = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        showSin = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        showEp = new javax.swing.JTextArea();
        epInput = new javax.swing.JTextField();
        selectEp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        showNameOutput = new javax.swing.JLabel();
        epNameOutput = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        epSinopsis = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        filePath = new javax.swing.JTextField();
        open = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(790, 600));
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Saman Prime");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 70));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setForeground(new java.awt.Color(204, 204, 204));

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        all.setBackground(new java.awt.Color(0, 0, 51));
        all.setForeground(new java.awt.Color(204, 204, 204));
        all.setText("Ver Todas las Series");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        jPanel2.add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 50));

        child.setBackground(new java.awt.Color(0, 0, 51));
        child.setForeground(new java.awt.Color(204, 204, 204));
        child.setText("Ver Series Infantiles");
        child.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childActionPerformed(evt);
            }
        });
        jPanel2.add(child, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 50));

        adult.setBackground(new java.awt.Color(0, 0, 51));
        adult.setForeground(new java.awt.Color(204, 204, 204));
        adult.setText("Ver Series Adultos");
        adult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultActionPerformed(evt);
            }
        });
        jPanel2.add(adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 50));

        filterOutput.setEditable(false);
        filterOutput.setColumns(20);
        filterOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        filterOutput.setRows(5);
        jScrollPane1.setViewportView(filterOutput);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 370, 320));

        allbyEp.setBackground(new java.awt.Color(0, 0, 51));
        allbyEp.setForeground(new java.awt.Color(204, 204, 204));
        allbyEp.setText("Ver Series por Numero de Capitulos");
        allbyEp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allbyEpActionPerformed(evt);
            }
        });
        jPanel2.add(allbyEp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Visualiza todas las series segun el filtro que desees que se encuentran cargadas a nuestro sistema!");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Descendente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 120, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Ascendente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 120, -1));

        jTabbedPane1.addTab("Ver Series por Tipo", jPanel2);

        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showInput.setText("Escribir nombre de la serie... ");
        jPanel4.add(showInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 320, -1));

        searchShow.setBackground(new java.awt.Color(0, 0, 51));
        searchShow.setForeground(new java.awt.Color(204, 204, 204));
        searchShow.setText("Buscar");
        searchShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchShowActionPerformed(evt);
            }
        });
        jPanel4.add(searchShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 130, -1));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        showSin.setEditable(false);
        showSin.setColumns(20);
        showSin.setRows(5);
        jScrollPane2.setViewportView(showSin);

        jSplitPane1.setTopComponent(jScrollPane2);

        showEp.setEditable(false);
        showEp.setColumns(20);
        showEp.setRows(5);
        jScrollPane3.setViewportView(showEp);

        jSplitPane1.setBottomComponent(jScrollPane3);

        jPanel4.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 320, 250));

        epInput.setText("Escribir nombre del capitulo...");
        jPanel4.add(epInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 310, -1));

        selectEp.setBackground(new java.awt.Color(0, 0, 51));
        selectEp.setForeground(new java.awt.Color(204, 204, 204));
        selectEp.setText("Seleccionar");
        selectEp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEpActionPerformed(evt);
            }
        });
        jPanel4.add(selectEp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel2.setText("Sinopsis de la Serie:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 240, -1));
        jPanel4.add(showNameOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 40));
        jPanel4.add(epNameOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 300, 40));

        epSinopsis.setEditable(false);
        epSinopsis.setColumns(20);
        epSinopsis.setRows(5);
        jScrollPane4.setViewportView(epSinopsis);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 310, 120));

        jLabel3.setText("Sinopsis del Capitulo:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 310, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 51));
        jTextArea1.setRows(5);
        jTextArea1.setText("Descubre las sinopsis y capitulos disponibles de las series de nuestro sistema!\nBusca por nombre la serie de la que deseas conocer mas informacion.  Para visualizar la descripcion de un capitulo, \ningresa el nombre una vez que hayas buscado la serie que deseas ver.");
        jScrollPane5.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 700, 50));

        jTabbedPane1.addTab("Seleccionar Serie", jPanel4);

        jPanel5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filePath.setEditable(false);
        filePath.setForeground(new java.awt.Color(0, 0, 51));
        jPanel5.add(filePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 300, -1));

        open.setBackground(new java.awt.Color(0, 0, 51));
        open.setForeground(new java.awt.Color(204, 204, 204));
        open.setText("Abrir Archivo");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jPanel5.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 150, -1));

        jLabel4.setText("Por favor seleccione el archivo de texto que contiene la informacion de las series disponibles");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 540, 80));

        create.setBackground(new java.awt.Color(0, 0, 51));
        create.setForeground(new java.awt.Color(204, 204, 204));
        create.setText("Confirmar");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel5.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Mediante esta funcion vas a poder cargar el archivo txt que contiene toda la informacion referente a las series y sus capitulos disponibles.");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTabbedPane1.addTab("Cargar Series", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 790, 520));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 10, 70, 20));

        status.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        status.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 260, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        JFileChooser chooser = new JFileChooser();
        if(chooser.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
            file=chooser.getSelectedFile();
            filePath.setText(file.getAbsolutePath());
        }
        else{
            JOptionPane.showMessageDialog(null, "No file selected");
        }
    }//GEN-LAST:event_openActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        ShowList= new ShowList();
        functions.read_file(file, ShowList);
        status.setText("");
    }//GEN-LAST:event_createActionPerformed

    private void childActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childActionPerformed
       if(ShowList!=null){
        
        filterOutput.setText(ShowList.print_kids());}
       else{
          filterOutput.setText("SIN INFORMACION CARGADA"); 
       }
    }//GEN-LAST:event_childActionPerformed

    private void adultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultActionPerformed
       if(ShowList!=null){
        
        filterOutput.setText(ShowList.print_adults());}
       else{
          filterOutput.setText("SIN INFORMACION CARGADA"); 
       }
    }//GEN-LAST:event_adultActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        if(ShowList!=null){
        
        filterOutput.setText(ShowList.print_all());}
       else{
          filterOutput.setText("SIN INFORMACION CARGADA"); 
       }
    }//GEN-LAST:event_allActionPerformed

    private void allbyEpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allbyEpActionPerformed
     if(ShowList!=null){
        
        filterOutput.setText(ShowList.print_with_chapters());
        jButton3.setVisible(true);
        jButton2.setVisible(true);}
       else{
          filterOutput.setText("SIN INFORMACION CARGADA"); 
         
       }
    }//GEN-LAST:event_allbyEpActionPerformed

    private void searchShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchShowActionPerformed
        if(ShowList!=null){
        String showN = functions.fix_input(showInput.getText());
        show= ShowList.search(showN);
        if(show!=null){
        showNameOutput.setText(show.getName().toUpperCase());
        showSin.setText(functions.make_readable(show.getSinopsis()));
        showEp.setText(show.print_episodes());}
        else{
            JOptionPane.showMessageDialog(null, "ERROR : Serie Invalida \n Asegurese de ingresar el nombre correcto");
            showInput.setText("Escribir nombre de la serie...");
            showNameOutput.setText("");
            showSin.setText("");
            showEp.setText("");
            epInput.setText("Escribir nombre del capitulo... ");
            epNameOutput.setText("");
            epSinopsis.setText("");
        }}
        else{
            epInput.setText("Escribir nombre del capitulo... ");
            epNameOutput.setText("");
            epSinopsis.setText("");
            showInput.setText("Escribir nombre de la serie...");
            showNameOutput.setText("");
            showSin.setText("");
            showEp.setText("");
            JOptionPane.showMessageDialog(null, "ERROR \n Asegurese de haber cargado informacion");
        }
    }//GEN-LAST:event_searchShowActionPerformed

    private void selectEpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEpActionPerformed
        if(ShowList!=null){
            if(show!=null){
        String epN = functions.fix_input(epInput.getText());
        NodoEp wanted = show.getEpisodes().search(epN);
        if(wanted!=null){
        epNameOutput.setText(wanted.getName().toUpperCase());
        epSinopsis.setText(functions.make_readable(wanted.getSinopsis()));
        }
        else{
            JOptionPane.showMessageDialog(null, "ERROR : Capitulo Invalido \n Asegurese de ingresar el nombre correcto");
            epInput.setText("Escribir nombre del capitulo... ");
            epNameOutput.setText("");
            epSinopsis.setText("");
        }}
        else{
            JOptionPane.showMessageDialog(null, "ERROR \n Recuerde buscar la serie que desea visualizar");
            epInput.setText("Escribir nombre del capitulo... ");
            epNameOutput.setText("");
            epSinopsis.setText("");
        }}
        else{
            JOptionPane.showMessageDialog(null, "ERROR \n Asegurese de haber cargado informacion");
        }
    }//GEN-LAST:event_selectEpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(ShowList!=null){
        
        filterOutput.setText(ShowList.print_with_chapters());}
       else{
          filterOutput.setText("SIN INFORMACION CARGADA"); 
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(ShowList!=null){
        
        filterOutput.setText(ShowList.printb_with_chapters());}
       else{
          filterOutput.setText("SIN INFORMACION CARGADA"); 
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adult;
    private javax.swing.JButton all;
    private javax.swing.JButton allbyEp;
    private javax.swing.JButton child;
    private javax.swing.JButton create;
    private javax.swing.JTextField epInput;
    private javax.swing.JLabel epNameOutput;
    private javax.swing.JTextArea epSinopsis;
    private javax.swing.JTextField filePath;
    private javax.swing.JTextArea filterOutput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton open;
    private javax.swing.JButton searchShow;
    private javax.swing.JButton selectEp;
    private javax.swing.JTextArea showEp;
    private javax.swing.JTextField showInput;
    private javax.swing.JLabel showNameOutput;
    private javax.swing.JTextArea showSin;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
